name: Build Dolphin Libretro (Android ARMv7)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r21e

      - name: Install deps
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build pkg-config

      - name: Configure & Build (ARMv7)
        run: |
          mkdir -p build && cd build
          cmake .. -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=armeabi-v7a \
            -DANDROID_PLATFORM=android-19 \
            -DCMAKE_BUILD_TYPE=Release
          cmake --build . -- -j2

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: dolphin-libretro-armv7
          path: build/dolphin_libretro_android.so
