name: Build Dolphin Libretro (Android ARMv7)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source with submodules
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r27c   # آخر إصدار ثابت للـ NDK

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y cmake ninja-build pkg-config

      - name: Configure & Build (ARMv7)
        run: |
          mkdir -p build && cd build
          cmake .. \
            -G Ninja \
            -DCMAKE_TOOLCHAIN_FILE=$ANDROID_NDK_HOME/build/cmake/android.toolchain.cmake \
            -DANDROID_ABI=armeabi-v7a \
            -DANDROID_PLATFORM=android-21 \
            -DCMAKE_BUILD_TYPE=Release \
            -DENABLE_JIT=OFF \
            -DLIBRETRO=ON
          ninja -j2

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: dolphin-libretro-armv7
          path: build/dolphin_libretro_android.so
